### ISSUE TITLE
OptionalCallExpression missing arguments

### ISSUE THREAD

**Issue by pvdz** [pvdz/tenko#13]
```js
const a = {};
$(a().b?.().c().d);
```

**Comment by pvdz** [comment]
Ahw, it's worse than that. A fix should be easy.

```
$ ./t i 'const a = {}; $(a().b?.().c().d);'
+ case "${ACTION}" in
+ node --experimental-modules --max-old-space-size=8192 tests/run_tests.mjs -i 'const a = {}; $(a().b?.().c().d);'
Start of Tenko test suite
Using override input and only testing that...
Sloppy mode implied (override with --strict or --module)
=============================================

Input size: 33 bytes


Error in parser: Assertion fail: Expecting to close a node with given name(s), expected: CallExpression but closed: OptionalCallExpression; [] remaining throw args; [ ':' ]
Error at:
`````
start@1:0, error@1:29
╔══╦═════════════════
 1 ║ const a = {}; $(a().b?.().c().d);
   ║                              ^------- error
╚══╩═════════════════
`````

Pure Tenko parse time: 6.786ms
####
An assertion error was thrown in sloppy mode with annexB=false

Input:

`````
const a = {}; $(a().b?.().c().d);
`````

Error message:

Parser error! Assertion fail: Expecting to close a node with given name(s), expected: CallExpression but closed: OptionalCallExpression; []

start@1:0, error@1:29
╔══╦═════════════════
 1 ║ const a = {}; $(a().b?.().c().d);
   ║                              ^------- error
╚══╩═════════════════

####
Error: Parser error! Assertion fail: Expecting to close a node with given name(s), expected: CallExpression but closed: OptionalCallExpression; []

start@1:0, error@1:29
╔══╦═════════════════
 1 ║ const a = {}; $(a().b?.().c().d);
   ║                              ^------- error
╚══╩═════════════════

    at _THROW (~/tenko/src/lexer.mjs:5332:45)
    at THROW_RANGE (~/tenko/src/parser.mjs:671:5)
    at ASSERT (~/tenko/src/parser.mjs:645:7)
    at AST_close (~/tenko/src/parser.mjs:797:5)
    at parseOptionalValueTailOuter (~/tenko/src/parser.mjs:8809:11)
    at parseValueTail (~/tenko/src/parser.mjs:8633:16)
    at _parseValueTailDotProperty (~/tenko/src/parser.mjs:8890:12)
    at parseValueTail (~/tenko/src/parser.mjs:8613:16)
    at _parseValueTailCall (~/tenko/src/parser.mjs:8943:12)
    at parseValueTail (~/tenko/src/parser.mjs:8617:16)
    at parseValue (~/tenko/src/parser.mjs:7588:12)
    at parseExpression (~/tenko/src/parser.mjs:7047:22)
    at parseCallArgs (~/tenko/src/parser.mjs:9090:31)
    at _parseValueTailCall (~/tenko/src/parser.mjs:8939:25)
    at parseValueTail (~/tenko/src/parser.mjs:8617:16)
    at parseValueAfterIdent (~/tenko/src/parser.mjs:7597:12)
    at parseExpressionAfterIdent (~/tenko/src/parser.mjs:7063:22)
    at parseExpressionsAfterIdent (~/tenko/src/parser.mjs:7393:32)
    at parseIdentLabelOrExpressionStatement (~/tenko/src/parser.mjs:6364:5)
    at parseIdentStatement (~/tenko/src/parser.mjs:3487:5)
    at parseBodyPart (~/tenko/src/parser.mjs:2726:7)
    at parseBodyPartsWithDirectives (~/tenko/src/parser.mjs:2625:7)
    at parseTopLevels (~/tenko/src/parser.mjs:2027:5)
    at Parser (~/tenko/src/parser.mjs:13412:3)
    at coreTest (~/tenko/tests/run_tests.mjs:254:9)
    at ~/tenko/tests/run_tests.mjs:558:47
    at Array.map (<anonymous>)
    at runTest (~/tenko/tests/run_tests.mjs:549:26)
    at runTests (~/tenko/tests/run_tests.mjs:674:25)
    at cli (~/tenko/tests/run_tests.mjs:834:9)
FAIL 
Hard exit() node now because: postProcessResult assertion error
```
